version: "3.3"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=my_store_graphql
      - POSTGRES_USER=felipe
      - POSTGRES_PASSWORD=123456
    ports:
      - 5433:5432
    volumes:
      - my-store-graphql-volume:/var/lib/postgresql/data

volumes:
  my-store-graphql-volume:
